### ISSUE TITLE
Unable to use this package in Vue2 based on readme setup

### ISSUE THREAD

**Issue by cennis-ck** [imgix/vue#464] opened 2022-11-15 15:52 UTC
When following the readme steps on the Vue2 branch, on multiple applications the below error is thrown:

```Uncaught TypeError: (0 , vue__WEBPACK_IMPORTED_MODULE_0__.defineComponent) is not a function
    at eval (imgix-vue.esm.js?e43c:1654:28)
    at ./node_modules/@imgix/vue/dist/imgix-vue.esm.js (app.js?clear=1668527166:19:1)
    at __webpack_require__ (app.js?clear=1668527166:6760:42)
    at eval (webpack-internal:///./resources/assets/js/app.js:23:69)
    at ./resources/assets/js/app.js (app.js?clear=1668527166:709:1)
    at __webpack_require__ (app.js?clear=1668527166:6760:42)
    at app.js?clear=1668527166:6939:313
    at __webpack_require__.O (app.js?clear=1668527166:6797:23)
    at app.js?clear=1668527166:6950:53
    at app.js?clear=1668527166:6952:12
```

in my app.js:

```
import VueImgix from '@imgix/vue';

Vue.use(VueImgix, {
  domain: "ourdomain.imgix.net",
  defaultIxParams: {
    // This enables the auto format imgix parameter by default for all images, which we recommend to reduce image size, but you might choose to turn this off.
    auto: 'format',
  },
});
```

current vue version: 
"vue": "^2.5.17",

**Comment by atlawrie** [comment] 2022-11-15 19:40
Hi @cennis-ck, thank you for letting us know about the issue! I've let the team know, and we'll update this thread with any new information.

**Comment by sherwinski** [comment] 2022-11-17 04:25
Hey @cennis-ck,

I noticed that the docs on our Vue2 branch might be unclear about which version of the library to install. Can you try installing the latest v2 version and report back whether that helps resolve your issue? Thanks

```
npm i @imgix/vue@2.9.0
```

**Comment by luqven** [comment] 2022-12-14 19:00
Hey @cennis-ck, I'm checking in again on this issue.

I cannot reproduce your error on Vue version `^2.5.17`. I think @sherwinski is probably right. You've likely installed the wrong version. Our docs for Vue 2 should be more explicit on that point.

You can find a simple Vue 2 codesandbox example [here](https://codesandbox.io/s/cocky-thunder-okfsyk?file=/src/App.vue).


I'm going to go ahead and close this for now, but should anything else come up, please don't hesitate to comment.

**Closed by luqven** 2022-12-14 19:00 UTC
Labels: bug, documentation
